name: Build RF Bot EXE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Visual Studio Build Tools
        run: |
          choco install visualstudio2022buildtools --package-parameters "--includeRecommended --includeOptional"
          Write-Output "Build Tools установлены."

      - name: Locate vcvarsall.bat
        id: find_vc
        shell: powershell
        run: |
          $paths = @(
            "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvarsall.bat",
            "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvarsall.bat",
            "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat"
          )

          foreach ($path in $paths) {
            if (Test-Path $path) {
              echo "VCPATH=$path" >> $env:GITHUB_ENV
              echo "Найдено: $path"
              exit 0
            }
          }

          echo "vcvarsall.bat не найден!"
          exit 1

      - name: Compile EXE
        shell: cmd
        run: |
          call "%VCPATH%" x64
          cd D:\a\rf-bot-cpp\rf-bot-cpp
          cl /EHsc /W4 /nologo /DUNICODE /D_UNICODE main.cpp user32.lib gdi32.lib /Fe:rf-bot.exe

      - name: Upload EXE
        uses: actions/upload-artifact@v3
        with:
          name: rf-bot-exe
          path: rf-bot.exe
